lint:
  rules:
    no_default: true
    add:
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - ORDER
      - PACKAGE_NAME_LOWER_CASE
      - RPC_NAMES_UPPER_CAMEL_CASE
      - RPC_NAMES_UPPER_CAMEL_CASE
      - QUOTE_CONSISTENT
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      # - PACKAGE_DIRECTORY_MATCH
      # - REPEATED_FIELD_NAMES_PLURALIZED
      # - INDENT
      # - IMPORTS_SORTED
      # - ENUM_FIELD_NAMES_PREFIX
