// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repository

import (
	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID `json:"id"`
	Text      string    `json:"text"`
	PostID    uuid.UUID `json:"post_id"`
	CreatorID string    `json:"creator_id"`
}
