// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repository

import (
	"database/sql"
	"time"
)

type DidMapping struct {
	Did         string       `json:"did"`
	LongFormUri string       `json:"long_form_uri"`
	Document    []byte       `json:"document"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

type DidToMessage struct {
	Did     string `json:"did"`
	Message string `json:"message"`
}
