// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countPostLikesStmt, err = db.PrepareContext(ctx, countPostLikes); err != nil {
		return nil, fmt.Errorf("error preparing query CountPostLikes: %w", err)
	}
	if q.deleteLikeStmt, err = db.PrepareContext(ctx, deleteLike); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLike: %w", err)
	}
	if q.likeStmt, err = db.PrepareContext(ctx, like); err != nil {
		return nil, fmt.Errorf("error preparing query Like: %w", err)
	}
	if q.listLikesStmt, err = db.PrepareContext(ctx, listLikes); err != nil {
		return nil, fmt.Errorf("error preparing query ListLikes: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countPostLikesStmt != nil {
		if cerr := q.countPostLikesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPostLikesStmt: %w", cerr)
		}
	}
	if q.deleteLikeStmt != nil {
		if cerr := q.deleteLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLikeStmt: %w", cerr)
		}
	}
	if q.likeStmt != nil {
		if cerr := q.likeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing likeStmt: %w", cerr)
		}
	}
	if q.listLikesStmt != nil {
		if cerr := q.listLikesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLikesStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db DBTX
	tx *sql.Tx
	countPostLikesStmt *sql.Stmt
	deleteLikeStmt     *sql.Stmt
	likeStmt           *sql.Stmt
	listLikesStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                 tx,
		tx:                 tx,
		countPostLikesStmt: q.countPostLikesStmt,
		deleteLikeStmt:     q.deleteLikeStmt,
		likeStmt:           q.likeStmt,
		listLikesStmt:      q.listLikesStmt,
	}
}
