// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repository

import (
	"github.com/google/uuid"
)

type Like struct {
	PostID uuid.UUID `json:"post_id"`
	UserID string    `json:"user_id"`
}
